### ISSUE TITLE
Create Unit test for About your work Page

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#106]
About your work

a) Next question button - error messages show if fields are empty
b) “Are you a healthcare worker?” question check drop-down menu options
c) “Do you care for multiple people in the community, with direct contact with your patients?” question check drop-down menu options
d) Next question button navigates to next screen

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
