### ISSUE TITLE
Create Unit test for About you Page

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#107]
About you
a) Year of birth validation (empty, date in the future, must have length of at least 4, check min age limit for app)
b) Sex - can’t be empty -error message
c) Sex - check drop-down options
d) Gender - can’t be empty -error message
e) Gender - check drop-down options
f) Height - can’t be empty -error message
g) Height - currently no validation
h) Height - change ft to cm
i) Weight - can’t be empty  -error message 
j) Weight - currently no validation
k) Weight - change lbs to kg
l) Postcode - currently no validation
m) Postcode - can’t be empty -error message
n) COVID-19 infection question can’t be empty -error message
o) COVID-19 infection question -check drop-down options
p) Next button

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
