### ISSUE TITLE
Create Unit test for About you health

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#109]
About your health

General question -check drop-down options
Heart disease question -check drop-down options
Diabetes question -check drop-down options
Asthma question -check drop-down options
Smoking question -check drop-down options
Kidney disease question -check drop-down options
Cancer question -check drop-down options
Medications -check drop-down options
Already had COVID-19 question -check drop-down options

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
