### ISSUE TITLE
Create Unit test for Describe symptoms page

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#113]
Describe symptoms page

a) “Do you have a fever?” question -check drop-down options
b) Temperature change C to F
c) Temperature -allowed numbers only
d) Symptoms questions -check drop-down options

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
