### ISSUE TITLE
Create Unit test for "Where are you right now.." Page

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#114]
"Where are you right now.." Page

a) “I’m at home”
b) “I’m at the hospital” -navigate to “What treatment are you receiving...” Page
c) “I’m back from the hospital I’d like to tell you about my treatment.” -navigate to “What treatment did you receive..” Page
d) “I’m back from the hospital I’ve already told you about my treatment.” - navigate to “Thank you..” page

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
