### ISSUE TITLE
Create Unit test for " “What treatment did you receive..” Page 

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#115]
“What treatment did you receive..” Page

a) None -navigate to the “Thank you..” Page
b) Oxygen and fluids -navigate to the “Thank you..” Page
c) Non-invasive ventilation -navigate to the “Thank you..” Page
d) Invasive ventilation -navigate to the “Thank you..” Page
e) Other -navigate optional text filed page
f) Other optional text field - done button

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
