### ISSUE TITLE
Step 7. npm run mock-server TSError 

### ISSUE THREAD

**Issue by bche1132** [zoe/covid-tracker-react-native#1155]
```
'.../covid-tracker-react-native/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)....'
```

Not sure if this is supposed to be happening when trying to run Step 7. npm run mock-server since the note below it is very vague. If this is known and does not effect the build, suggest updating documentation and making the note below more clear.

**Comment by selvach** [comment]
Fixed with https://github.com/zoe/covid-tracker-react-native/pull/1589
