### ISSUE TITLE
Disable button CTA on About You screen

### ISSUE THREAD

**Issue by emma3333** [zoe/covid-tracker-react-native#155]
Related to issue #90 but breaking down into smaller issues by screen. This one is for the About You screen.

From issue #90 - If the screen contains mandatory questions that have not been answered yet, CTA should be in a disabled state (Disabled state CTA colour is #C7CED8).

<img width="386" alt="Screenshot 2020-04-24 at 09 49 55" src="https://user-images.githubusercontent.com/35655626/80193611-08e4cd80-8611-11ea-9e0d-273077946269.png">

**Comment by julienlavigne** [comment]
Thanks for creating the issue @emma3333, it's indeed a lot better to split by screen :-)
