### ISSUE TITLE
Add checkmark for profiles reported today

### ISSUE THREAD

**Issue by selvach** [zoe/covid-tracker-react-native#177]
Add green tick when user has reported for today on the Select Profile Screen. 
  
![Screenshot 2020-04-25 at 19 15 35](https://user-images.githubusercontent.com/7824212/80287373-2ad17380-8729-11ea-95c0-aa29a3d39ec2.png)

**Comment by bpiggin** [comment]
PR here: https://github.com/zoe/covid-tracker-react-native/pull/284
