### ISSUE TITLE
Use SVG instead of PNG in icons and flags

### ISSUE THREAD

**Issue by grifotv** [zoe/covid-tracker-react-native#182]
I believe it would be better to use SVG as it would allow UI elements such as icons and flags to be resizable and have dynamic colour props potentially (eg: avatar component could have single SVG with dynamic colours).

It would also ensure flags would be displayed as sharp as possible in retina devices rather than pixelated as the screenshot below:

![image](https://user-images.githubusercontent.com/435351/80305305-ec34cb00-87b3-11ea-8015-2aeb2c95637a.png)

Please let me know your thoughts.

**Comment by selvach** [comment]
Fixed!
