### ISSUE TITLE
Update textfields styling (textfields / error states / dropdowns) to match design

### ISSUE THREAD

**Issue by livalana** [zoe/covid-tracker-react-native#230]
Currently, textfield & dropdown cells styling do not match designs. Can these be updated across all screens to match designs?

Figma link for design specs: https://www.figma.com/file/QfnykTJefcuWa8L1oOjZDz/Text-fields-styling?node-id=0%3A1

Designs reference:

![Dropdowns](https://user-images.githubusercontent.com/12391240/81161022-d1681080-8f82-11ea-83a3-90d1259c70b5.jpg)
![Textfield](https://user-images.githubusercontent.com/12391240/81161025-d2993d80-8f82-11ea-8f32-85498d34fb40.jpg)

**Comment by selvach** [comment]
Hey @CristianMaschio - We rolled this out to 3.5million users last week and it was really well received. Thank you so much for your help!
