### ISSUE TITLE
Signup / Login not working with password managers

### ISSUE THREAD

**Issue by selvach** [zoe/covid-tracker-react-native#34]

**Comment by louiechristie** [comment]
I did manage to use 1Password to sign up on the production app, but with a couple of small issues.

Environment:
App: COVID Symptom Study version 1.9 (Production App Store App)
Password manager: 1Password 7.5.2
OS: iOS 13.4.1
Browser: Safari

Issues:

1. In 1Password when clicking Create Login, the name of the app, and the website were not auto populated.
1. When logging in to 1Password with password (Face ID works ok) intermittently the keyboard overlaid the password box, blocking view. But I don't think this is an issue with COVID app, think that is an issue with Safari, iOS or 1Password.
