### ISSUE TITLE
Display username/email address in menu

### ISSUE THREAD

**Issue by MikeD-ZOE** [zoe/covid-tracker-react-native#53]
Display logged in username/email address in the menu.
* When a user logs in, or registers, store the username/email address in AsyncStorage
* If the username/email address is in AsyncStorage, display it in the menu
* Delete the username/email address from AsyncStorage when the user logs out, or deletes their data

**Comment by mnecchi** [comment]
@MikeD-ZOE Is there a mock up for this?

**Comment by mnecchi** [comment]
@selvach @julienlavigne @MikeD-ZOE Is there a design mock up for how to display the username and email in the menu?
