### ISSUE TITLE
Create Unit test for sign up for an account

### ISSUE THREAD

**Issue by ZoltanTAB** [zoe/covid-tracker-react-native#86]
Scenarios for unit test:

Create a new account
a) Valid email address
b) Empty email field -error message
c) Empty password field - error message

Password must be at least 8 characters with letters (TBC)
d) Password is less than 8 characters - error message
e) Password is 8 characters or more
f) Create account button
g) Log in button

**Comment by abubuwe** [comment]
Thank you for creating this issue. 
We are reviewing our approach to testing + will update the guidance around testing once that is completed.
