### ISSUE TITLE
Update typeface to Sofia Pro

### ISSUE THREAD

**Issue by livalana** [zoe/covid-tracker-react-native#92]
COVID app typeface should be Sophis Pro (attached)
[Fonts.zip](https://github.com/zoe/covid-tracker-react-native/files/4557059/Fonts.zip)

**Comment by grifotv** [comment]
I’m happy to do this one.

Do we have the appropriate license to use this font in this product?

Would be good to know what font family variations we should use (eg: share designs)

**Comment by livalana** [comment]
Hey, sorry for the delay. 

Yes, we have a licence for app & web use up to 5million users. 

See a screenshot attached for a visual reference. 
![How do you feel physically right now_](https://user-images.githubusercontent.com/12391240/80688087-31fad780-8ac3-11ea-82b4-d488cea2bf53.png)

Goog alternative will be Google Font Open Sans (https://fonts.google.com/specimen/Open+Sans)
and Manrope (https://fonts.google.com/specimen/Manrope)

**Comment by julienlavigne** [comment]
BTW, first step would be this I think: https://medium.com/@martin_adamko/consistent-font-line-height-rendering-42068cc2957d
